### ISSUE TITLE
Your personal website is down

### ISSUE THREAD

**Issue by imfromthenet** [alexanderby/mova#3]
Hi, Alexander,

sorry for contacting you here, but I don't have LinkedIn premium and I tried different email addresses for you personal website, but none worked.

I just wanted to inform you that your personal website is down. 

I am getting:
```
Forbidden
You don't have permission to access / on this server.
```
have a good day

**Comment by alexanderby** [comment]
Hi Paulius, thanks for noticing. Don't worry, I still haven't uploaded anything there.
